### ISSUE TITLE
Consider using official microprofile?

### ISSUE THREAD

**Issue by vinjn** [dougbinks/microprofile#2]
It's also hosted in github and actively maintained.
https://github.com/jonasmr/microprofile

**Comment by dougbinks** [comment]
The main reason I haven't moved to using Jonas' microprofile on github is
that since I forked it from the Bitbucket repo the code has evolved in a
direction which doesn't suit my needs - namely the in-app profile drawing
has been removed in favour of improved web and offline profile viewing.

Since my main use of Microprofile is for quick in-app viewing of profiling
I've decided to stick with the older forked code. For more complex
screnarios I recommend either switching to Jonas' microprofile branch on
Github or using Intel's Vtune or Intel GPA trace analyzer.

**Comment by vinjn** [comment]
I see, that makes sense.
